---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kubeflow-instance
  namespace: ${releaseNamespace}
spec:
  interval: 1m0s
  ref:
    branch: main
  timeout: 15m0s
  url: http://172.18.229.52:3000/gitea/kubeflow.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubeflow-instance
  namespace: ${releaseNamespace}
spec:
  patches:
  - patch: |
      - op: replace
        path: /spec/type
        value: LoadBalancer
    target:
      kind: Service
      name: istio-ingressgateway
      namespace: istio-system
  - patch: |
     - op: add
       path: /metadata/namespace
       value: default
    target:
      kind: ConfigMap
      name: default-install-config.*
  interval: 6h
  timeout: 15m0s
  path: ./manifests/example
  prune: true
  serviceAccountName: ${releaseNamespace}
  sourceRef:
   kind: GitRepository
   name: kubeflow-instance
   namespace: ${releaseNamespace}

